<a href="https://colab.research.google.com/github/Sanjivkumar100/IPL-Sponsorship-Value-Intelligence-Dashboard/blob/main/BusinessIntelligenceDataCollection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Match Data

In [ ]:
!pip install opendatasets

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from opendatasets) (4.67.3)
Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (from opendatasets) (2.0.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from opendatasets) (8.3.3)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (6.3.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.19.1)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (0.1.20)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (26.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.32.4)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle->opendatasets) (4.0.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle->opendatasets) (0.5.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle->opendatasets) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle->opendatasets) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle->opendatasets) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (3.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (2026.4.22)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle->opendatasets) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle->opendatasets) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle->opendatasets) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle->opendatasets) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle->opendatasets) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle->opendatasets) (4.9.6)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (4.15.0)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [1]:
import google.colab
google.colab.drive.mount('/content/drive')

Mounted at /content/drive

In [65]:
import pandas as pd
ipl_matches=pd.read_csv('/content/drive/MyDrive/IPL.csv')
ipl_matches.head()

/tmp/ipykernel_530/1443155164.py:2: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  ipl_matches=pd.read_csv('/content/drive/MyDrive/IPL.csv')

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,131970,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,131971,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,131972,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,131973,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,131974,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [ ]:
ipl_matches.columns

Index(['Unnamed: 0', 'match_id', 'date', 'match_type', 'event_name', 'innings',
       'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
       'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
       'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
       'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
       'player_out', 'fielders', 'runs_target', 'review_batter',
       'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
       'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
       'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter', 'batter_runs',
       'batter_balls', 'bowler_wicket', 'batting_partners', 'next_batter',
       'striker_out'],
      dtype='object')

In [66]:
match_df=ipl_matches.groupby('match_id').agg({
    'date':'first',
    'batting_team':'first',
    'bowling_team':'first',
    'venue':'first',
    'city':'first',
    'player_of_match':'first',
    'match_won_by':'first',
    'win_outcome':'first'
}).reset_index()
match_df.head()

,match_id,date,batting_team,bowling_team,venue,city,player_of_match,match_won_by,win_outcome
0,335982,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,BB McCullum,Kolkata Knight Riders,140 runs
1,335983,2008-04-19,Chennai Super Kings,Kings XI Punjab,"Punjab Cricket Association Stadium, Mohali",Chandigarh,MEK Hussey,Chennai Super Kings,33 runs
2,335984,2008-04-19,Rajasthan Royals,Delhi Daredevils,Feroz Shah Kotla,Delhi,MF Maharoof,Delhi Daredevils,9 wickets
3,335985,2008-04-20,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai,MV Boucher,Royal Challengers Bangalore,5 wickets
4,335986,2008-04-20,Deccan Chargers,Kolkata Knight Riders,Eden Gardens,Kolkata,DJ Hussey,Kolkata Knight Riders,5 wickets

In [67]:
match_df.rename(columns={
    'batting_team':'team1',
    'bowling_team':'team2',
    'match_won_by':'match_winner'
},inplace=True)

In [68]:
match_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   match_id         1169 non-null   int64
 1   date             1169 non-null   object
 2   team1            1169 non-null   object
 3   team2            1169 non-null   object
 4   venue            1169 non-null   object
 5   city             1169 non-null   object
 6   player_of_match  1169 non-null   object
 7   match_winner     1169 non-null   object
 8   win_outcome      1146 non-null   object
dtypes: int64(1), object(8)
memory usage: 82.3+ KB

In [69]:
match_df['date']=pd.to_datetime(match_df['date'])
match_df

,match_id,date,team1,team2,venue,city,player_of_match,match_winner,win_outcome
0,335982,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,BB McCullum,Kolkata Knight Riders,140 runs
1,335983,2008-04-19,Chennai Super Kings,Kings XI Punjab,"Punjab Cricket Association Stadium, Mohali",Chandigarh,MEK Hussey,Chennai Super Kings,33 runs
2,335984,2008-04-19,Rajasthan Royals,Delhi Daredevils,Feroz Shah Kotla,Delhi,MF Maharoof,Delhi Daredevils,9 wickets
3,335985,2008-04-20,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai,MV Boucher,Royal Challengers Bangalore,5 wickets
4,335986,2008-04-20,Deccan Chargers,Kolkata Knight Riders,Eden Gardens,Kolkata,DJ Hussey,Kolkata Knight Riders,5 wickets
...,...,...,...,...,...,...,...,...,...
1164,1473508,2025-05-29,Punjab Kings,Royal Challengers Bengaluru,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,Suyash Sharma,Royal Challengers Bengaluru,8 wickets
1165,1473509,2025-05-30,Mumbai Indians,Gujarat Titans,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,RG Sharma,Mumbai Indians,20 runs
1166,1473510,2025-06-01,Mumbai Indians,Punjab Kings,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,SS Iyer,Punjab Kings,5 wickets
1167,1473511,2025-06-03,Royal Challengers Bengaluru,Punjab Kings,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,KH Pandya,Royal Challengers Bengaluru,6 runs
1168,1485779,2025-05-24,Punjab Kings,Delhi Capitals,"Sawai Mansingh Stadium, Jaipur",Jaipur,Sameer Rizvi,Delhi Capitals,6 wickets

In [70]:
match_df['team1'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Mumbai Indians', 'Deccan Chargers', 'Kings XI Punjab',
       'Royal Challengers Bangalore', 'Delhi Daredevils',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [71]:
match_df['team2'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Kolkata Knight Riders', 'Rajasthan Royals',
       'Mumbai Indians', 'Chennai Super Kings', 'Deccan Chargers',
       'Pune Warriors', 'Kochi Tuskers Kerala', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Gujarat Titans', 'Lucknow Super Giants',
       'Royal Challengers Bengaluru'], dtype=object)

In [72]:
match_df.loc[match_df['team1']=='Delhi Daredevils', 'team1']= 'Delhi Capitals'
match_df.loc[match_df['team1']=='Kings XI Punjab', 'team1']= 'Punjab Kings'
match_df.loc[match_df['team1']=='Royal Challengers Bangalore', 'team1']= 'Royal Challengers Bengaluru'

In [73]:
match_df.loc[match_df['team2']=='Delhi Daredevils', 'team2']= 'Delhi Capitals'
match_df.loc[match_df['team2']=='Kings XI Punjab', 'team2']= 'Punjab Kings'
match_df.loc[match_df['team2']=='Royal Challengers Bangalore', 'team2']= 'Royal Challengers Bengaluru'
match_df.loc[match_df['team1']=='Rising Pune Supergiant', 'team1']= 'Rising Pune Supergiants'
match_df.loc[match_df['team2']=='Rising Pune Supergiant', 'team2']= 'Rising Pune Supergiants'

In [74]:
stadium_capacity = {
    "MA Chidambaram Stadium": 50000,
    "Wankhede Stadium": 33000,
    "Narendra Modi Stadium": 132000,
    "Arun Jaitley Stadium": 41000,
    "Dubai International Cricket Stadium": 25000,
    "Zayed Cricket Stadium": 20000,
    "Sharjah Cricket Stadium": 16000,
    "Brabourne Stadium": 20000,
    "Dr DY Patil Sports Academy": 55000,
    "Maharashtra Cricket Association Stadium": 37000,
    "Eden Gardens": 68000,
    "Punjab Cricket Association IS Bindra Stadium": 26000,
    "Ekana Cricket Stadium": 50000,
    "Rajiv Gandhi International Stadium": 55000,
    "M Chinnaswamy Stadium": 40000,
    "Barsapara Cricket Stadium": 40000,
    "Sawai Mansingh Stadium": 30000,
    "Himachal Pradesh Cricket Association Stadium": 23000,
    "ACA-VDCA Cricket Stadium": 28000,
    "Maharaja Yadavindra Singh International Cricket Stadium": 38000
}

In [75]:
match_df['venue'] = match_df['venue'].str.split(',').str[0].str.strip()

match_df['venue']=match_df['venue'].replace(
    {
      "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium": "Ekana Cricket Stadium",
    "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium": "ACA-VDCA Cricket Stadium",
    "Zayed Cricket Stadium, Abu Dhabi": "Zayed Cricket Stadium"

    }
)

In [76]:
match_df['attendance_proxy']=match_df['venue'].map(stadium_capacity)
match_df['attendance_proxy'].isnull().sum()

np.int64(275)

In [77]:
match_df['attendance_proxy'].fillna(30000,inplace=True)

/tmp/ipykernel_530/1640071008.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  match_df['attendance_proxy'].fillna(30000,inplace=True)

In [78]:
filtered_match_df=match_df[(match_df['date']>=pd.to_datetime('2021-02-01'))&
 (match_df['date']<=pd.to_datetime('2026-03-30'))
 ]

In [16]:
filtered_match_df.head()

,match_id,date,team1,team2,venue,city,player_of_match,match_winner,win_outcome,attendance_proxy
816,1254058,2021-04-09,Mumbai Indians,Royal Challengers Bengaluru,MA Chidambaram Stadium,Chennai,HV Patel,Royal Challengers Bangalore,2 wickets,50000.0
817,1254059,2021-04-10,Chennai Super Kings,Delhi Capitals,Wankhede Stadium,Mumbai,S Dhawan,Delhi Capitals,7 wickets,33000.0
818,1254060,2021-04-11,Kolkata Knight Riders,Sunrisers Hyderabad,MA Chidambaram Stadium,Chennai,N Rana,Kolkata Knight Riders,10 runs,50000.0
819,1254061,2021-04-12,Punjab Kings,Rajasthan Royals,Wankhede Stadium,Mumbai,SV Samson,Punjab Kings,4 runs,33000.0
820,1254062,2021-04-13,Mumbai Indians,Kolkata Knight Riders,MA Chidambaram Stadium,Chennai,RD Chahar,Mumbai Indians,10 runs,50000.0

In [17]:
!pip install pytrends

Collecting pytrends
  Downloading pytrends-4.9.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: requests>=2.0 in /usr/local/lib/python3.12/dist-packages (from pytrends) (2.32.4)
Requirement already satisfied: pandas>=0.25 in /usr/local/lib/python3.12/dist-packages (from pytrends) (2.2.2)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from pytrends) (6.1.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25->pytrends) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25->pytrends) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25->pytrends) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25->pytrends) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0->pytrends) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0->pytrends) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0->pytrends) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0->pytrends) (2026.4.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25->pytrends) (1.17.0)
Downloading pytrends-4.9.2-py3-none-any.whl (15 kB)
Installing collected packages: pytrends
Successfully installed pytrends-4.9.2

In [79]:
from pytrends.request import TrendReq

pytrends = TrendReq(hl='en_Us',tz=330)

teams=['Chennai Super Kings',"Mumbai Indians",'Royal Challengers Bengaluru','Delhi Capitals','Kolkata Knight Riders']

pytrends.build_payload(teams, timeframe='2021-02-01 2026-03-30')

data=pytrends.interest_over_time()
data.head()

,Chennai Super Kings,Mumbai Indians,Royal Challengers Bengaluru,Delhi Capitals,Kolkata Knight Riders,isPartial
date,,,,,,
2021-01-31,0,1,0,0,0,False
2021-02-07,0,1,0,0,0,False
2021-02-14,3,5,0,2,1,False
2021-02-21,1,2,0,1,0,False
2021-02-28,0,1,0,0,0,False

In [80]:
data

,Chennai Super Kings,Mumbai Indians,Royal Challengers Bengaluru,Delhi Capitals,Kolkata Knight Riders,isPartial
date,,,,,,
2021-01-31,0,1,0,0,0,False
2021-02-07,0,1,0,0,0,False
2021-02-14,3,5,0,2,1,False
2021-02-21,1,2,0,1,0,False
2021-02-28,0,1,0,0,0,False
...,...,...,...,...,...,...
2026-03-01,1,2,0,1,1,False
2026-03-08,3,4,1,1,1,False
2026-03-15,3,6,1,2,1,False
2026-03-22,5,8,43,3,2,False
2026-03-29,100,71,18,50,54,False

In [81]:
merged=pd.merge(filtered_match_df,data,on='date',how="left")
merged.head()

,match_id,date,team1,team2,venue,city,player_of_match,match_winner,win_outcome,attendance_proxy,Chennai Super Kings,Mumbai Indians,Royal Challengers Bengaluru,Delhi Capitals,Kolkata Knight Riders,isPartial
0,1254058,2021-04-09,Mumbai Indians,Royal Challengers Bengaluru,MA Chidambaram Stadium,Chennai,HV Patel,Royal Challengers Bangalore,2 wickets,50000.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1254059,2021-04-10,Chennai Super Kings,Delhi Capitals,Wankhede Stadium,Mumbai,S Dhawan,Delhi Capitals,7 wickets,33000.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1254060,2021-04-11,Kolkata Knight Riders,Sunrisers Hyderabad,MA Chidambaram Stadium,Chennai,N Rana,Kolkata Knight Riders,10 runs,50000.0,4.0,15.0,0.0,6.0,3.0,False
3,1254061,2021-04-12,Punjab Kings,Rajasthan Royals,Wankhede Stadium,Mumbai,SV Samson,Punjab Kings,4 runs,33000.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1254062,2021-04-13,Mumbai Indians,Kolkata Knight Riders,MA Chidambaram Stadium,Chennai,RD Chahar,Mumbai Indians,10 runs,50000.0,NaN,NaN,NaN,NaN,NaN,NaN

In [82]:
merged.fillna(0,inplace=True)

In [83]:
merged

,match_id,date,team1,team2,venue,city,player_of_match,match_winner,win_outcome,attendance_proxy,Chennai Super Kings,Mumbai Indians,Royal Challengers Bengaluru,Delhi Capitals,Kolkata Knight Riders,isPartial
0,1254058,2021-04-09,Mumbai Indians,Royal Challengers Bengaluru,MA Chidambaram Stadium,Chennai,HV Patel,Royal Challengers Bangalore,2 wickets,50000.0,0.0,0.0,0.0,0.0,0.0,0
1,1254059,2021-04-10,Chennai Super Kings,Delhi Capitals,Wankhede Stadium,Mumbai,S Dhawan,Delhi Capitals,7 wickets,33000.0,0.0,0.0,0.0,0.0,0.0,0
2,1254060,2021-04-11,Kolkata Knight Riders,Sunrisers Hyderabad,MA Chidambaram Stadium,Chennai,N Rana,Kolkata Knight Riders,10 runs,50000.0,4.0,15.0,0.0,6.0,3.0,False
3,1254061,2021-04-12,Punjab Kings,Rajasthan Royals,Wankhede Stadium,Mumbai,SV Samson,Punjab Kings,4 runs,33000.0,0.0,0.0,0.0,0.0,0.0,0
4,1254062,2021-04-13,Mumbai Indians,Kolkata Knight Riders,MA Chidambaram Stadium,Chennai,RD Chahar,Mumbai Indians,10 runs,50000.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,1473508,2025-05-29,Punjab Kings,Royal Challengers Bengaluru,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,Suyash Sharma,Royal Challengers Bengaluru,8 wickets,38000.0,0.0,0.0,0.0,0.0,0.0,0
349,1473509,2025-05-30,Mumbai Indians,Gujarat Titans,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,RG Sharma,Mumbai Indians,20 runs,38000.0,0.0,0.0,0.0,0.0,0.0,0
350,1473510,2025-06-01,Mumbai Indians,Punjab Kings,Narendra Modi Stadium,Ahmedabad,SS Iyer,Punjab Kings,5 wickets,132000.0,2.0,49.0,57.0,2.0,1.0,False
351,1473511,2025-06-03,Royal Challengers Bengaluru,Punjab Kings,Narendra Modi Stadium,Ahmedabad,KH Pandya,Royal Challengers Bengaluru,6 runs,132000.0,0.0,0.0,0.0,0.0,0.0,0
352,1485779,2025-05-24,Punjab Kings,Delhi Capitals,Sawai Mansingh Stadium,Jaipur,Sameer Rizvi,Delhi Capitals,6 wickets,30000.0,0.0,0.0,0.0,0.0,0.0,0

In [84]:
merged.drop(['isPartial'],axis=1,inplace=True)

In [85]:
merged.sort_values(by='date',inplace=True)

In [86]:
merged

,match_id,date,team1,team2,venue,city,player_of_match,match_winner,win_outcome,attendance_proxy,Chennai Super Kings,Mumbai Indians,Royal Challengers Bengaluru,Delhi Capitals,Kolkata Knight Riders
0,1254058,2021-04-09,Mumbai Indians,Royal Challengers Bengaluru,MA Chidambaram Stadium,Chennai,HV Patel,Royal Challengers Bangalore,2 wickets,50000.0,0.0,0.0,0.0,0.0,0.0
1,1254059,2021-04-10,Chennai Super Kings,Delhi Capitals,Wankhede Stadium,Mumbai,S Dhawan,Delhi Capitals,7 wickets,33000.0,0.0,0.0,0.0,0.0,0.0
2,1254060,2021-04-11,Kolkata Knight Riders,Sunrisers Hyderabad,MA Chidambaram Stadium,Chennai,N Rana,Kolkata Knight Riders,10 runs,50000.0,4.0,15.0,0.0,6.0,3.0
3,1254061,2021-04-12,Punjab Kings,Rajasthan Royals,Wankhede Stadium,Mumbai,SV Samson,Punjab Kings,4 runs,33000.0,0.0,0.0,0.0,0.0,0.0
4,1254062,2021-04-13,Mumbai Indians,Kolkata Knight Riders,MA Chidambaram Stadium,Chennai,RD Chahar,Mumbai Indians,10 runs,50000.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,1473507,2025-05-27,Lucknow Super Giants,Royal Challengers Bengaluru,Ekana Cricket Stadium,Lucknow,JM Sharma,Royal Challengers Bengaluru,6 wickets,50000.0,0.0,0.0,0.0,0.0,0.0
348,1473508,2025-05-29,Punjab Kings,Royal Challengers Bengaluru,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,Suyash Sharma,Royal Challengers Bengaluru,8 wickets,38000.0,0.0,0.0,0.0,0.0,0.0
349,1473509,2025-05-30,Mumbai Indians,Gujarat Titans,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,RG Sharma,Mumbai Indians,20 runs,38000.0,0.0,0.0,0.0,0.0,0.0
350,1473510,2025-06-01,Mumbai Indians,Punjab Kings,Narendra Modi Stadium,Ahmedabad,SS Iyer,Punjab Kings,5 wickets,132000.0,2.0,49.0,57.0,2.0,1.0
351,1473511,2025-06-03,Royal Challengers Bengaluru,Punjab Kings,Narendra Modi Stadium,Ahmedabad,KH Pandya,Royal Challengers Bengaluru,6 runs,132000.0,0.0,0.0,0.0,0.0,0.0

In [87]:
merged['city'].unique()

array(['Chennai', 'Mumbai', 'Ahmedabad', 'Delhi', 'Dubai', 'Abu Dhabi',
       'Sharjah', 'Pune', 'Navi Mumbai', 'Kolkata', 'Chandigarh',
       'Lucknow', 'Hyderabad', 'Bengaluru', 'Guwahati', 'Jaipur',
       'Dharamsala', 'Mohali', 'Visakhapatnam', 'New Chandigarh'],
      dtype=object)

In [88]:
merged['venue'].unique()

array(['MA Chidambaram Stadium', 'Wankhede Stadium',
       'Narendra Modi Stadium', 'Arun Jaitley Stadium',
       'Dubai International Cricket Stadium', 'Zayed Cricket Stadium',
       'Sharjah Cricket Stadium', 'Brabourne Stadium',
       'Dr DY Patil Sports Academy',
       'Maharashtra Cricket Association Stadium', 'Eden Gardens',
       'Punjab Cricket Association IS Bindra Stadium',
       'Ekana Cricket Stadium', 'Rajiv Gandhi International Stadium',
       'M Chinnaswamy Stadium', 'Barsapara Cricket Stadium',
       'Sawai Mansingh Stadium',
       'Himachal Pradesh Cricket Association Stadium',
       'Maharaja Yadavindra Singh International Cricket Stadium',
       'ACA-VDCA Cricket Stadium'], dtype=object)

In [89]:
from google.colab import userdata

api_key = userdata.get("YOUTUBE_API_KEY")

In [90]:
from googleapiclient.discovery import build

youtube = build('youtube', 'v3', developerKey=api_key)

In [91]:
team_data=[]
for team in teams:
  print(f"Fetching data for {team}")
  request=youtube.search().list(
      q=f'{team}ipl highlights',
      part='snippet',
      type='video',
      maxResults=20
  )
  response= request.execute()

  video_ids=[]
  channel_ids=set()
  for item in response['items']:
    video_ids.append(item['id']['videoId'])
    channel_ids.add(item['snippet']['channelId'])

  stats_request=youtube.videos().list(
      part="statistics",
      id=",".join(video_ids)
  )
  stats_response=stats_request.execute()

  for item in stats_response['items']:
    stats=item['statistics']

    views=int(stats.get('viewCount',0))
    likes=int(stats.get('likeCount',0))
    comments=int(stats.get('commentCount',0))

    team_data.append([team,views,likes,comments])

df=pd.DataFrame(team_data,columns=['team','views','likes','comments'])

df['views']=df['views'].fillna(0)
df['likes']=df['likes'].fillna(0)
df['comments']=df['comments'].fillna(0)
df['engagement']=((df['likes']+df['comments'])/df['views'])*100
df['engagement'] = df['engagement'].fillna(0)

teams_engagement = df.groupby('team').agg({
    'views':'mean',
    'likes':'mean',
    'comments':'mean',
    'engagement':'mean'
}).reset_index()

teams_engagement

Fetching data for Chennai Super Kings
Fetching data for Mumbai Indians
Fetching data for Royal Challengers Bengaluru
Fetching data for Delhi Capitals
Fetching data for Kolkata Knight Riders

                          team       views    likes  comments  engagement
0          Chennai Super Kings  1405077.95  33224.1    445.60    1.833111
1               Delhi Capitals  3244937.85  71192.1    143.95    1.385749
2        Kolkata Knight Riders  1225839.45  29661.8     57.05    1.086341
3               Mumbai Indians  4471239.50  88423.5    280.35    1.154240
4  Royal Challengers Bengaluru  3520602.75  94399.7    836.25    2.219569

In [92]:
def get_popularity(row):
  t1=row['team1']
  t2=row['team2']
  return(row.get(t1,0)+row.get(t2,0))/2
merged['popularity_score']=merged.apply(get_popularity,axis=1)

In [93]:
# Merge team1
final_df = pd.merge(
    merged,
    teams_engagement,
    left_on='team1',
    right_on='team',
    how='left'
)

# Merge team2
final_df = pd.merge(
    merged,
    teams_engagement,
    left_on='team2',
    right_on='team',
    how='left',
    suffixes=('_team1', '_team2')
)

In [94]:
final_df

,match_id,date,team1,team2,venue,city,player_of_match,match_winner,win_outcome,attendance_proxy,...,Mumbai Indians,Royal Challengers Bengaluru,Delhi Capitals,Kolkata Knight Riders,popularity_score,team,views,likes,comments,engagement
0,1254058,2021-04-09,Mumbai Indians,Royal Challengers Bengaluru,MA Chidambaram Stadium,Chennai,HV Patel,Royal Challengers Bangalore,2 wickets,50000.0,...,0.0,0.0,0.0,0.0,0.0,Royal Challengers Bengaluru,3520602.75,94399.7,836.25,2.219569
1,1254059,2021-04-10,Chennai Super Kings,Delhi Capitals,Wankhede Stadium,Mumbai,S Dhawan,Delhi Capitals,7 wickets,33000.0,...,0.0,0.0,0.0,0.0,0.0,Delhi Capitals,3244937.85,71192.1,143.95,1.385749
2,1254060,2021-04-11,Kolkata Knight Riders,Sunrisers Hyderabad,MA Chidambaram Stadium,Chennai,N Rana,Kolkata Knight Riders,10 runs,50000.0,...,15.0,0.0,6.0,3.0,1.5,NaN,NaN,NaN,NaN,NaN
3,1254061,2021-04-12,Punjab Kings,Rajasthan Royals,Wankhede Stadium,Mumbai,SV Samson,Punjab Kings,4 runs,33000.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,1254062,2021-04-13,Mumbai Indians,Kolkata Knight Riders,MA Chidambaram Stadium,Chennai,RD Chahar,Mumbai Indians,10 runs,50000.0,...,0.0,0.0,0.0,0.0,0.0,Kolkata Knight Riders,1225839.45,29661.8,57.05,1.086341
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,1473507,2025-05-27,Lucknow Super Giants,Royal Challengers Bengaluru,Ekana Cricket Stadium,Lucknow,JM Sharma,Royal Challengers Bengaluru,6 wickets,50000.0,...,0.0,0.0,0.0,0.0,0.0,Royal Challengers Bengaluru,3520602.75,94399.7,836.25,2.219569
349,1473508,2025-05-29,Punjab Kings,Royal Challengers Bengaluru,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,Suyash Sharma,Royal Challengers Bengaluru,8 wickets,38000.0,...,0.0,0.0,0.0,0.0,0.0,Royal Challengers Bengaluru,3520602.75,94399.7,836.25,2.219569
350,1473509,2025-05-30,Mumbai Indians,Gujarat Titans,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,RG Sharma,Mumbai Indians,20 runs,38000.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
351,1473510,2025-06-01,Mumbai Indians,Punjab Kings,Narendra Modi Stadium,Ahmedabad,SS Iyer,Punjab Kings,5 wickets,132000.0,...,49.0,57.0,2.0,1.0,24.5,NaN,NaN,NaN,NaN,NaN
352,1473511,2025-06-03,Royal Challengers Bengaluru,Punjab Kings,Narendra Modi Stadium,Ahmedabad,KH Pandya,Royal Challengers Bengaluru,6 runs,132000.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN

In [95]:
print(set(final_df['team1']) - set(teams_engagement['team']))

{'Gujarat Titans', 'Punjab Kings', 'Sunrisers Hyderabad', 'Rajasthan Royals', 'Lucknow Super Giants'}

In [96]:
final_df = final_df[
    final_df['team1'].isin(teams_engagement['team']) &
    final_df['team2'].isin(teams_engagement['team'])
]

In [38]:
final_df = final_df.drop_duplicates()

In [97]:
final_df.columns

Index(['match_id', 'date', 'team1', 'team2', 'venue', 'city',
       'player_of_match', 'match_winner', 'win_outcome', 'attendance_proxy',
       'Chennai Super Kings', 'Mumbai Indians', 'Royal Challengers Bengaluru',
       'Delhi Capitals', 'Kolkata Knight Riders', 'popularity_score', 'team',
       'views', 'likes', 'comments', 'engagement'],
      dtype='object')

In [98]:
# Merge team1
final_df = pd.merge(
    final_df,
    teams_engagement,
    left_on='team1',
    right_on='team',
    how='left'
)

# Merge team2
final_df = pd.merge(
    final_df,
    teams_engagement,
    left_on='team2',
    right_on='team',
    how='left',
    suffixes=('_team1', '_team2')
)

In [101]:
final_df['match_engagement']=((final_df['engagement_x']+final_df['engagement_y'])/2)

In [102]:
final_df[['team1', 'team2', 'match_engagement']]

                          team1                        team2  match_engagement
0                Mumbai Indians  Royal Challengers Bengaluru          1.686905
1           Chennai Super Kings               Delhi Capitals          1.609430
2                Mumbai Indians        Kolkata Knight Riders          1.120291
3   Royal Challengers Bengaluru        Kolkata Knight Riders          1.652955
4                Mumbai Indians               Delhi Capitals          1.269994
..                          ...                          ...               ...
80               Delhi Capitals  Royal Challengers Bengaluru          1.802659
81        Kolkata Knight Riders               Delhi Capitals          1.236045
82  Royal Challengers Bengaluru          Chennai Super Kings          2.026340
83        Kolkata Knight Riders          Chennai Super Kings          1.459726
84               Mumbai Indians               Delhi Capitals          1.269994

[85 rows x 3 columns]

In [103]:
final_df.rename(columns={
    'views_x': 'views_team1',
    'views_y': 'views_team2',
    'engagement_x': 'engagement_team1',
    'engagement_y': 'engagement_team2'
}, inplace=True)

In [107]:
final_df['SVI'] = (
    0.4 * final_df['attendance_proxy'] +
    0.3 * final_df['popularity_score'] +
    0.3 * final_df['match_engagement']
)

In [106]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

final_df[['attendance_proxy',
          'popularity_score',
          'match_engagement']] = scaler.fit_transform(

    final_df[['attendance_proxy',
              'popularity_score',
              'match_engagement']]
)

In [108]:
final_df

,match_id,date,team1,team2,venue,city,player_of_match,match_winner,win_outcome,attendance_proxy,...,likes_y,comments_y,engagement_team2,team,views,likes,comments,engagement,match_engagement,SVI
0,1254058,2021-04-09,Mumbai Indians,Royal Challengers Bengaluru,MA Chidambaram Stadium,Chennai,HV Patel,Royal Challengers Bangalore,2 wickets,0.293103,...,88423.5,280.35,1.154240,Royal Challengers Bengaluru,3520602.75,94399.7,836.25,2.219569,0.625368,0.304852
1,1254059,2021-04-10,Chennai Super Kings,Delhi Capitals,Wankhede Stadium,Mumbai,S Dhawan,Delhi Capitals,7 wickets,0.146552,...,33224.1,445.60,1.833111,Delhi Capitals,3244937.85,71192.1,143.95,1.385749,0.539859,0.220578
2,1254062,2021-04-13,Mumbai Indians,Kolkata Knight Riders,MA Chidambaram Stadium,Chennai,RD Chahar,Mumbai Indians,10 runs,0.293103,...,88423.5,280.35,1.154240,Kolkata Knight Riders,1225839.45,29661.8,57.05,1.086341,0.000000,0.117241
3,1254067,2021-04-18,Royal Challengers Bengaluru,Kolkata Knight Riders,MA Chidambaram Stadium,Chennai,AB de Villiers,Royal Challengers Bangalore,38 runs,0.293103,...,94399.7,836.25,2.219569,Kolkata Knight Riders,1225839.45,29661.8,57.05,1.086341,0.587898,0.299166
4,1254070,2021-04-20,Mumbai Indians,Delhi Capitals,MA Chidambaram Stadium,Chennai,A Mishra,Delhi Capitals,6 wickets,0.293103,...,88423.5,280.35,1.154240,Delhi Capitals,3244937.85,71192.1,143.95,1.385749,0.165227,0.166809
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,1473483,2025-04-27,Delhi Capitals,Royal Challengers Bengaluru,Arun Jaitley Stadium,Delhi,KH Pandya,Royal Challengers Bengaluru,6 wickets,0.215517,...,71192.1,143.95,1.385749,Royal Challengers Bengaluru,3520602.75,94399.7,836.25,2.219569,0.753125,0.612144
81,1473485,2025-04-29,Kolkata Knight Riders,Delhi Capitals,Arun Jaitley Stadium,Delhi,SP Narine,Kolkata Knight Riders,14 runs,0.215517,...,29661.8,57.05,1.086341,Delhi Capitals,3244937.85,71192.1,143.95,1.385749,0.127757,0.124534
82,1473489,2025-05-03,Royal Challengers Bengaluru,Chennai Super Kings,M Chinnaswamy Stadium,Bengaluru,R Shepherd,Royal Challengers Bengaluru,2 runs,0.206897,...,94399.7,836.25,2.219569,Chennai Super Kings,1405077.95,33224.1,445.60,1.833111,1.000000,0.382759
83,1473494,2025-05-07,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Kolkata,Noor Ahmad,Chennai Super Kings,2 wickets,0.448276,...,29661.8,57.05,1.086341,Chennai Super Kings,1405077.95,33224.1,445.60,1.833111,0.374632,0.291700
84,1473501,2025-05-21,Mumbai Indians,Delhi Capitals,Wankhede Stadium,Mumbai,SA Yadav,Mumbai Indians,59 runs,0.146552,...,88423.5,280.35,1.154240,Delhi Capitals,3244937.85,71192.1,143.95,1.385749,0.165227,0.108189

In [109]:
final_df.to_csv('BusinessIntelligence_IPL.csv')